<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="TestSuite" duration-ms="103" started-at="2019-04-11T18:49:28Z" finished-at="2019-04-11T18:49:28Z">
    <groups>
    </groups>
    <test name="alok" duration-ms="103" started-at="2019-04-11T18:49:28Z" finished-at="2019-04-11T18:49:28Z">
      <class name="org.testng.com.Demo.Test1">
        <test-method status="PASS" signature="te()[pri:0, instance:org.testng.com.Demo.Test1@100fc185]" name="te" duration-ms="7" started-at="2019-04-12T00:19:28Z" finished-at="2019-04-12T00:19:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- te -->
        <test-method status="FAIL" signature="tse()[pri:0, instance:org.testng.com.Demo.Test1@100fc185]" name="tse" duration-ms="19" started-at="2019-04-12T00:19:28Z" finished-at="2019-04-12T00:19:28Z">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:92)
	at org.junit.Assert.assertTrue(Assert.java:43)
	at org.junit.Assert.assertTrue(Assert.java:54)
	at org.testng.com.Demo.Test1.tse(Test1.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tse -->
      </class> <!-- org.testng.com.Demo.Test1 -->
      <class name="org.testng.com.Demo.alok">
        <test-method status="PASS" signature="s()[pri:0, instance:org.testng.com.Demo.alok@402f32ff]" name="s" duration-ms="25" started-at="2019-04-12T00:19:28Z" finished-at="2019-04-12T00:19:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- s -->
      </class> <!-- org.testng.com.Demo.alok -->
    </test> <!-- alok -->
  </suite> <!-- TestSuite -->
</testng-results>
